import { Song } from "../types";

const songs: Song[] = [
  {
    title: "Soca Soca do Submundo (Shark Version)",
    artists: "Victor Lou, MC Theuzyn",
    cover: "src/assets/cover/socaSocaShark.webp",
    audio: "src/assets/audio/socaSocaShark.ogg",
    link: "https://open.spotify.com/intl-pt/album/1KLyYfUuBmnSlwNEhtnaVU?si=7aVIx_lXRO6ENQM56T1a3A",
  },{
    title: "Soca Soca do Submundo (Funk Version)",
    artists: "Victor Lou, dJ GBR, MC Theuzyn",
    cover: "src/assets/cover/socaSocaFunk.webp",
    audio: "src/assets/audio/socaSocaFunk.ogg",
    link: "https://open.spotify.com/intl-pt/album/6i4F2LcrVKA9I5ltZAEHWu?si=hBMQWm0IS-erHnM9XA34Zw",
  },{
    title: "Untitled (Trance Remix)",
    artists: "Victor Lou, Mazuk",
    cover: "src/assets/cover/untitled(TranceRemix).webp",
    audio: "src/assets/audio/untitled(TranceRemix).ogg",
    link: "https://open.spotify.com/intl-pt/album/6n9HAIjtM3wF1AY8QfXv7p",
  },{
    title: "Baile Lotadão",
    artists: "Victor Lou, Gesualdi",
    cover: "src/assets/cover/baileLotadao.webp",
    audio: "src/assets/audio/baileLotadao.ogg",
    link: "https://open.spotify.com/intl-pt/album/7LWs9wqCZIUPsZAllaKjEY",
  },{
    title: "Silver Stone",
    artists: "Victor Lou, Odaya",
    cover: "src/assets/cover/silverStone.webp",
    audio: "src/assets/audio/silverStone.ogg",
    link: "https://open.spotify.com/intl-pt/album/6TfU6xhKT4I7ptc5qeiG48",
  },{
    title: "Everything I Got",
    artists: "Victor Lou,",
    cover: "src/assets/cover/everythingIGot.webp",
    audio: "src/assets/audio/everythingIGot.ogg",
    link: "https://open.spotify.com/intl-pt/album/6XGsbOf23jgqWqyFxSvV8C",
  },{
    title: "Night Is Closing",
    artists: "Victor Lou",
    cover: "src/assets/cover/nightIsCLosing.webp",
    audio: "src/assets/audio/nightIsClosing.ogg",
    link: "https://open.spotify.com/intl-pt/album/3lDpGeWM1LS4mCF2qX8Hcw",
  },{
    title: "Kanyes",
    artists: "Victor Lou",
    cover: "src/assets/cover/kanyes.webp",
    audio: "src/assets/audio/kanyes.ogg",
    link: "https://open.spotify.com/intl-pt/album/6ePpI5BPsyDdFR3XpjESP2",
  },{
    title: "Dark Side",
    artists: "Victor Lou, Lori'S",
    cover: "src/assets/cover/darkSide.webp",
    audio: "src/assets/audio/darkSide.ogg",
    link: "https://open.spotify.com/intl-pt/album/5iPFyuo0C5zXRiNG8xjjTF?uid=96387ac4675ebd60bcc6&uri=spotify%3Atrack%3A3PuUTLpGpBS4YYKPJ1JQhN",
  },{
    title: "Closed Eyes",
    artists: "Victor Lou, Lori'S",
    cover: "src/assets/cover/darkSide.webp",
    audio: "src/assets/audio/closedEyes.ogg",
    link: "https://open.spotify.com/intl-pt/album/5iPFyuo0C5zXRiNG8xjjTF?uid=96387ac4675ebd60bcc6&uri=spotify%3Atrack%3A3PuUTLpGpBS4YYKPJ1JQhN",
  },{
    title: "Catedral",
    artists: "Victor Lou, Duarte",
    cover: "src/assets/cover/natural.webp",
    audio: "src/assets/audio/catedral.ogg",
    link: "https://open.spotify.com/intl-pt/album/2F7rJsdLsrnN7nuIM7Xwlk",
  },{
    title: "Game Boy",
    artists: "Victor Lou, Duarte, EVEL!N",
    cover: "src/assets/cover/natural.webp",
    audio: "src/assets/audio/gameBoy.ogg",
    link: "https://open.spotify.com/intl-pt/album/2F7rJsdLsrnN7nuIM7Xwlk",
  },{
    title: "Colors",
    artists: "Victor Lou, Duarte",
    cover: "src/assets/cover/natural.webp",
    audio: "src/assets/audio/colors.ogg",
    link: "https://open.spotify.com/intl-pt/album/2F7rJsdLsrnN7nuIM7Xwlk",
  },{
    title: "AMA",
    artists: "Victor Lou, Duarte",
    cover: "src/assets/cover/natural.webp",
    audio: "src/assets/audio/ama.ogg",
    link: "https://open.spotify.com/intl-pt/album/2F7rJsdLsrnN7nuIM7Xwlk",
  },{
    title: "Cigarrets",
    artists: "Victor Lou, Duarte",
    cover: "src/assets/cover/natural.webp",
    audio: "src/assets/audio/cigarrets.ogg",
    link: "https://open.spotify.com/intl-pt/album/2F7rJsdLsrnN7nuIM7Xwlk",
  },{
    title: "Vitoria",
    artists: "Victor Lou, Duarte",
    cover: "src/assets/cover/natural.webp",
    audio: "src/assets/audio/vitoria.ogg",
    link: "https://open.spotify.com/intl-pt/album/2F7rJsdLsrnN7nuIM7Xwlk",
  },{
    title: "Piloto",
    artists: "Victor Lou, Duarte, Yung Buda",
    cover: "src/assets/cover/piloto.webp",
    audio: "src/assets/audio/piloto.ogg",
    link: "https://open.spotify.com/intl-pt/album/3QvyoGqcvy6cy55J8nJSG7",
  },{
    title: "Intro",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23.webp",
    audio: "src/assets/audio/intro.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Dance",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23.webp",
    audio: "src/assets/audio/dance.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Remote Control",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23.webp",
    audio: "src/assets/audio/remoteControl.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },
  {
    title: "Paradise",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23.webp",
    audio: "src/assets/audio/paradise.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Shadowzada",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23.webp",
    audio: "src/assets/audio/shadowzada.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Bass Level",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23.webp",
    audio: "src/assets/audio/bassLevel.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Kill Bixo",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23(2).webp",
    audio: "src/assets/audio/killBixo.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "HM",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23(2).webp",
    audio: "src/assets/audio/hm.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Industry",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23(2).webp",
    audio: "src/assets/audio/industry.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Memories",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23(2).webp",
    audio: "src/assets/music/memories.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },{
    title: "Interlúdio",
    artists: "Victor Lou",
    cover: "src/assets/cover/may23(2).webp",
    audio: "src/assets/audio/interludio.ogg",
    link: "https://open.spotify.com/intl-pt/album/465uKcpgmFpMmcEAwIW8J1",
  },
];

export default songs;
